-- Create integration with AWS
CREATE or REPLACE STORAGE INTEGRATION s3_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<role_iam>'
  STORAGE_ALLOWED_LOCATIONS = ('*');
  -- STORAGE_BLOCKED_LOCATIONS = (');

DESC INTEGRATION s3_integration;